### ISSUE TITLE
Add design pattern details and  Deployement details to the README.md

### ISSUE THREAD

**Issue by chamodshehanka** [sliit-foss/RentLio#2]
Mention other Java software design patterns used in this project and add deployment  details.

**Comment by akash-vartak** [comment]
Hey @Shehanka @ntbandara3 , although those details mentioned in the issue are already present, I would love to format the README and make it better, the logo link is broken, the design patterns mentioned are bullet by icon and not by number, the deployment items are actually prerequisites. I am sending you a pull request with the changes done.

**Comment by nandunbandara** [comment]
Fixed in PR ^
